#!/usr/bin/env node
/**
 * Post the latest audit findings to a Slack channel via incoming webhook.
 *
 * Usage:
 *   notify-slack --findings <path> [--webhook-url <url>] [--severity-filter critical|high|medium]
 *
 * Resolves webhook URL from (in priority order):
 *   1. --webhook-url flag
 *   2. SLACK_WEBHOOK_URL env var
 *   3. .rugproof.yml notifications.slack.webhook_url
 */

import { readFile } from "node:fs/promises";
import { resolve } from "node:path";

const SEV_LEVEL: Record<string, number> = { info: 0, low: 1, medium: 2, high: 3, critical: 4 };
const SEV_EMOJI: Record<string, string> = {
  critical: ":no_entry:", high: ":warning:", medium: ":zap:", low: ":small_blue_diamond:", info: ":memo:",
};

function parseArgs(argv: string[]): Record<string, string> {
  const out: Record<string, string> = {};
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a.startsWith("--")) {
      const k = a.slice(2);
      const v = argv[i + 1] && !argv[i + 1].startsWith("--") ? argv[++i] : "true";
      out[k] = v;
    }
  }
  return out;
}

async function readWebhook(args: Record<string, string>): Promise<string> {
  if (args["webhook-url"]) return args["webhook-url"];
  if (process.env.SLACK_WEBHOOK_URL) return process.env.SLACK_WEBHOOK_URL;
  try {
    const cfg = await readFile(".rugproof.yml", "utf-8");
    const m = cfg.match(/slack:[\s\S]*?webhook_url:\s*["']?([^\s"']+)/);
    if (m) return m[1];
  } catch {}
  return "";
}

async function main() {
  const args = parseArgs(process.argv.slice(2));
  if (!args.findings) {
    console.error("usage: notify-slack --findings <path> [--webhook-url URL] [--severity-filter LEVEL]");
    process.exit(1);
  }

  const webhook = await readWebhook(args);
  if (!webhook) {
    console.error("error: no webhook URL. Set SLACK_WEBHOOK_URL, pass --webhook-url, or add to .rugproof.yml.");
    process.exit(1);
  }

  const findings = JSON.parse(await readFile(resolve(args.findings), "utf-8"));
  const minLevel = SEV_LEVEL[(args["severity-filter"] || "high").toLowerCase()] ?? 3;
  const filtered = (findings.findings || []).filter((f: any) => (SEV_LEVEL[(f.severity || "info").toLowerCase()] ?? 0) >= minLevel);

  const c = findings.counts || {};
  const top = filtered[0];

  const payload = {
    text: `🛡 Rugproof — ${findings.target ?? "audit"}`,
    blocks: [
      {
        type: "header",
        text: { type: "plain_text", text: `🛡 Rugproof — ${findings.target ?? "audit"}` },
      },
      {
        type: "section",
        fields: [
          { type: "mrkdwn", text: `*Critical:* ${c.critical ?? 0}` },
          { type: "mrkdwn", text: `*High:* ${c.high ?? 0}` },
          { type: "mrkdwn", text: `*Medium:* ${c.medium ?? 0}` },
          { type: "mrkdwn", text: `*Grade:* ${findings.grade ?? "?"}` },
        ],
      },
      ...(top ? [{
        type: "section" as const,
        text: { type: "mrkdwn" as const, text: `${SEV_EMOJI[(top.severity || "info").toLowerCase()] || ""} *${top.severity}* — \`${top.id}\` ${top.title}\n\`${top.path}:${top.line}\`` },
      }] : []),
      ...(filtered.length > 1 ? [{
        type: "context" as const,
        elements: [{ type: "mrkdwn" as const, text: `+ ${filtered.length - 1} more finding(s) at or above ${args["severity-filter"] ?? "high"} severity` }],
      }] : []),
      {
        type: "context",
        elements: [
          { type: "mrkdwn", text: `Generated by <https://github.com/omermaksutii/RugProof|Rugproof> · ${findings.date ?? new Date().toISOString().slice(0, 10)}` },
        ],
      },
    ],
  };

  const res = await fetch(webhook, {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify(payload),
  });

  if (!res.ok) {
    const body = await res.text();
    console.error(`✗ Slack webhook returned ${res.status}: ${body}`);
    process.exit(1);
  }

  console.log(`✓ posted ${filtered.length} finding(s) to Slack (target: ${findings.target ?? "—"})`);
}

main().catch((err) => { console.error("notify-slack failed:", err); process.exit(1); });
