#!/usr/bin/env node
// Generate the audit gallery page from docs/gallery/manifest.json so it grows by
// editing data, not HTML. Run from repo root: node scripts/generate-gallery.mjs
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve, join } from "node:path";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const GALLERY = join(ROOT, "docs", "gallery");
const manifest = JSON.parse(readFileSync(join(GALLERY, "manifest.json"), "utf-8"));

const esc = (s = "") =>
  String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");

const card = (e) => {
  const c = e.counts ?? {};
  const total = (c.critical ?? 0) + (c.high ?? 0) + (c.medium ?? 0) + (c.low ?? 0) + (c.info ?? 0);
  return `      <a class="sample-card" href="${esc(e.report)}">
        <img src="${esc(e.card)}" alt="${esc(e.target)} audit card" loading="lazy" width="600" height="600">
        <div class="sample-card-meta">
          <span class="rg-row"><span class="rg-grade rg-grade-${esc(e.grade).toLowerCase()}">${esc(e.grade)}</span><strong class="name">${esc(e.target)}</strong></span>
          <span class="rg-vuln">${esc(e.vuln)}</span>
          <span class="rg-counts">${c.critical ?? 0} critical · ${c.high ?? 0} high · ${total} total</span>
          <span class="rg-top">${esc(e.top_finding)}</span>
        </div>
      </a>`;
};

const html = `<!doctype html>
<html lang="en">
<head>
<base href="/RugProof/">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Audit Gallery — Rugproof</title>
<meta name="theme-color" content="#0a0904">
<link rel="icon" type="image/svg+xml" href="assets/favicon.svg">
<link rel="apple-touch-icon" href="assets/apple-touch-icon.png">
<link rel="stylesheet" href="assets/style.css">
<link rel="stylesheet" href="assets/gallery.css">
<!-- generated by scripts/generate-gallery.mjs from docs/gallery/manifest.json — do not edit by hand -->
<style>
  .sample-card-meta { display: flex; flex-direction: column; gap: 6px; padding: 14px 4px 4px; }
  .rg-row { display: flex; align-items: center; gap: 10px; }
  .rg-grade { font-weight: 800; border-radius: 6px; padding: 1px 9px; font-size: .85rem; color: #0a0904; background: var(--honey, #e8b923); }
  .rg-grade-f { background: #e5484d; color: #fff; }
  .rg-grade-d { background: #e5734d; color: #fff; }
  .rg-grade-c { background: #e8b923; }
  .rg-grade-b, .rg-grade-a { background: #46a758; color: #fff; }
  .sample-card-meta .name { font-size: 1.05rem; }
  .rg-vuln { color: var(--text-mid, #9a8f7a); font-size: .9rem; }
  .rg-counts { color: var(--text-dim, #6f6655); font-size: .8rem; font-variant-numeric: tabular-nums; }
  .rg-top { color: var(--text, #d8cdb8); font-size: .88rem; line-height: 1.35; }
</style>
</head>
<body>
<div class="bg-honeycomb"></div>
<div class="bg-grain"></div>

<nav class="nav">
  <div class="nav-inner">
    <a class="logo" href="index.html"><span class="logo-mark"></span>RUGPROOF</a>
    <div class="nav-links">
      <a href="index.html#features">features</a>
      <a href="gallery/" style="color: var(--honey);">gallery</a>
      <a href="docs/">docs</a>
      <a href="docs/commands.html">commands</a>
      <a class="cta" href="https://github.com/omermaksutii/RugProof">github →</a>
    </div>
  </div>
</nav>

<section class="block" style="padding-top: 80px;">
  <div class="container">
    <div class="section-head">
      <h2>Audit <span class="it">gallery.</span></h2>
      <p class="meta">
        ${manifest.entries.length} public audit cards. Run <code>/card --share gallery</code>
        after <code>/audit</code> to add your own (append to
        <code>docs/gallery/manifest.json</code> + <code>make gallery</code>).
      </p>
    </div>

    <div class="sample-grid">
${manifest.entries.map(card).join("\n")}
    </div>
  </div>
</section>

<footer>
  <div class="container">
    <div class="footer-bottom">
      <a href="index.html" style="color: var(--text-mid); text-decoration: none;">← back to home</a>
      <span>v0.8.0</span>
    </div>
  </div>
</footer>

<script src="assets/animations.js"></script>
</body>
</html>
`;

writeFileSync(join(GALLERY, "index.html"), html);
console.log(`✓ generated gallery: ${manifest.entries.length} card(s)`);
